version: "2"

services:
  nginx:
    image: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./app/static:/var/app/static
    ports:
      - "4000:80"
    links:
      - web1
      - web2

  web1:
    image: node
    command: "node /var/app/server1.js"
    volumes:
      - ./app:/var/app
    links:
      - redis
      
  web2:
    image: node
    command: "node /var/app/server2.js"
    volumes:
      - ./app:/var/app
    links:
      - redis

  redis:
    image: redis
    ports:
      - "6379"